// 导入必要的类型和字体组件
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// 配置Geist Sans字体
const geistSans = Geist({
  variable: "--font-geist-sans", // CSS变量名
  subsets: ["latin"], // 字体子集
});

// 配置Geist Mono字体（等宽字体）
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// 配置页面元数据
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// 根布局组件
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`} // 应用字体变量和抗锯齿
      >
        {children}
      </body>
    </html>
  );
}
